### ISSUE TITLE
Ashwin had trouble with openbabel on Docker

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/karr_lab_docker_images#1]
Perhaps we should
a) Update karr_lab_docker_images/README.md to instruct people to use the Docker image with the latest tag, and
b) Update the latest tag on https://hub.docker.com/r/karrlab/build/tags/

**Comment by jonrkarr** [comment]
We can certainly update the tag or delete it. But CircleCI recommends not
using the latest tag.

**Comment by jonrkarr** [comment]
Updated README and the script that builds the image to push the update tag.

Images can be pulled without the version tag. Pulling without a version tag
will pull the latest version:

> docker pull karrlab/build


To let docker use the latest version of each image, I think its best to
avoid using version tags in Dockerfiles ("FROM" directive) and README
files. Because "docker build" uses the latest version that's on your local
machine, you have to first run "docker pull" before running "docker build".

However, CircleCI config files should specify the version needed (e.g.
org/image:x.y.z) because CircleCI's caching system doesn't automatically
pull the latest version.
